spring:
  application:
    name: ms-config
    instance_id: 1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangfeishsh/config-repo.git
          username: baochunyu1987@163.com
          password: a10051544
#          basedir: target/config
          clone-on-start: true
          searchPaths: ms*
server:
  port: 9003

eureka:
  instance:
    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
#    region: default
#    registryFetchIntervalSeconds: 5
#    availabilityZones:
#      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    com.netflix.discovery: 'OFF'
